# Generated by Django 3.0 on 2020-01-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('a_subject', models.CharField(max_length=100)),
                ('a_no', models.IntegerField()),
                ('t_total', models.IntegerField()),
                ('t_mark', models.IntegerField()),
                ('b_batch', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'assesments',
            },
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_addno', models.IntegerField()),
                ('a_date', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('a_h1', models.CharField(max_length=10)),
                ('a_h2', models.CharField(max_length=10)),
                ('a_h3', models.CharField(max_length=10)),
                ('a_h4', models.CharField(max_length=10)),
                ('b_batch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attendance_table',
            },
        ),
        migrations.CreateModel(
            name='batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_batch', models.CharField(max_length=10)),
                ('b_nostudents', models.IntegerField()),
                ('b_incharge', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'batch_details',
            },
        ),
        migrations.CreateModel(
            name='faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_address', models.CharField(max_length=100)),
                ('f_gender', models.CharField(max_length=10)),
                ('f_mobile', models.IntegerField()),
                ('f_email', models.CharField(blank=True, max_length=50, null=True)),
                ('f_batch', models.CharField(max_length=10)),
                ('f_qualfication', models.CharField(max_length=10)),
                ('f_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'faculty_details',
            },
        ),
        migrations.CreateModel(
            name='facultyleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('f_name', models.CharField(max_length=50)),
                ('l_fromdate', models.CharField(max_length=50)),
                ('l_todate', models.CharField(max_length=50)),
                ('l_reason', models.CharField(max_length=500)),
                ('l_status', models.CharField(default='Pending', max_length=500)),
            ],
            options={
                'db_table': 'faculty_leave_details',
            },
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sign_up',
            },
        ),
        migrations.CreateModel(
            name='studentleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=50)),
                ('l_fromdate', models.CharField(max_length=50)),
                ('l_todate', models.CharField(max_length=50)),
                ('l_reason', models.CharField(max_length=500)),
                ('l_status', models.CharField(default='Pending', max_length=500)),
            ],
            options={
                'db_table': 'student_leave_details',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('s_addno', models.IntegerField(primary_key=True, serialize=False)),
                ('s_adddate', models.DateField()),
                ('s_name', models.CharField(max_length=50)),
                ('s_address', models.CharField(max_length=200)),
                ('s_gender', models.CharField(max_length=10)),
                ('s_dob', models.DateField()),
                ('s_guardian', models.CharField(max_length=50)),
                ('s_mobile', models.IntegerField()),
                ('s_email', models.EmailField(max_length=50)),
                ('b_batch', models.CharField(max_length=50)),
                ('s_qualfication', models.CharField(max_length=10)),
                ('s_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'students_details',
            },
        ),
    ]
